In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.insert(0,'../code')
import utils as ut
fn = 'input.txt'

## 1

In [3]:
inp = ut.rl(fn)

In [4]:
import numpy as np
head_pos = np.array([0,0])
tail_pos = np.array([0,0])
tail_poss = []

In [5]:
for inst in inp:
    dir, dist = inst.split(' ')
    dist = int(dist)
    for i in range(dist):
        if dir == 'R':
            head_pos[0] += 1
        elif dir == 'L':
            head_pos[0] -= 1
        elif dir == 'U':
            head_pos[1] += 1
        elif dir == 'D':
            head_pos[1] -= 1         
        
        posdiff = head_pos - tail_pos
        
        if posdiff[1] == 0 or posdiff[0] == 0:
            move = np.array([int(p/2) for p in posdiff])
            tail_pos += move
        elif abs(posdiff[0])<=1 and abs(posdiff[1])<=1:
            move = [0,0]
        else:
            move = np.array([int(p/2) if abs(p) == 2 else p for p in posdiff])
            tail_pos += move
        tail_poss.append([tail_pos[0],tail_pos[1]])

In [6]:
len(set([str(p) for p in tail_poss]))

6391

In [7]:
def plot_movement(v):
    ymin = np.array(v)[:,1].min()
    ymax = np.array(v)[:,1].max()
    xmin = np.array(v)[:,0].min()
    xmax = np.array(v)[:,0].max()
    mat = np.zeros((xmax-xmin+1,ymax-ymin+1))
    for pos in v:
        mat[pos[0]-xmin,pos[1]-ymin] = 1
    print(mat)

In [8]:
plot_movement(tail_poss)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## 2

In [9]:
def move_segment(head_pos,tail_pos):
    head_pos = np.array(head_pos)
    tail_pos = np.array(tail_pos)
    posdiff = head_pos - tail_pos

    if posdiff[1] == 0 or posdiff[0] == 0:
        move = np.array([int(p/2) for p in posdiff])
        tail_pos += move
    elif abs(posdiff[0])<=1 and abs(posdiff[1])<=1:
        move = [0,0]
    else:
        move = np.array([int(p/2) if abs(p) == 2 else p for p in posdiff])
        tail_pos += move
    return [tail_pos[0],tail_pos[1]]

In [10]:
fn = 'input.txt'
inp = ut.rl(fn)
positions = [[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]]
tail_poss = []
for inst in inp:
    dir, dist = inst.split(' ')
    dist = int(dist)
    for i in range(dist):
        if dir == 'R':
            positions[0][0] += 1
        elif dir == 'L':
            positions[0][0] -= 1
        elif dir == 'U':
            positions[0][1] += 1
        elif dir == 'D':
            positions[0][1] -= 1 
        for i,position in enumerate(positions):
            if i == 0:
                continue
            positions[i] = move_segment(positions[i-1],positions[i])
            #print(positions)
        tail_poss.append(positions[-1])

In [11]:
len(set([str(p) for p in tail_poss]))

2593